#!/bin/bash
#
# Clone the software and apply a commit after each patch
# The purpose is to easily rebuild the patches

# Install directory path
DIR="./draft/"
# Git directory path
GDIR=$PWD

function main(){
	# Cleanup dir
	echo "===== $1 ====="
	if test -d $DIR$1; then
		rm -rf $DIR$1
	fi
	# Clone
	mkdir -p $DIR$1
	git clone https://git.suckless.org/$1 $DIR$1
	# Patches
	for file in $GDIR/$1/patches/*; do
		set name (echo $file | sed -e 's/.*[0-9]-\(.*\)\.patch/\1/')
		echo "----- $name -----"
		patch -p1 -d $DIR$1 < $file
		git -C $DIR$1 commit -a -m "$name"
	done
}

if [ -z $1 ]; then
	for i in "dwm" "dmenu" "st"; do
		main $i
	done
else
	main $1
fi

# To get the patches :
# git format-patch origin/master -o ./patches/
